name: Flask Production Build
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8 
      
      - name: Create virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install gunicorn  # Add production WSGI server
          python -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
          python -m pip install gdown
      
      - name: Download model from Google Drive
        run: |
          mkdir -p models
          gdown https://drive.google.com/uc?id=1uw3bfSPDTOAKJusQ16gRfCSS5C9Gl7JS -O models/plant_disease_classification.pth
          ls -lh models/
      
      - name: Create production configuration
        run: |
          echo "FLASK_ENV=production" > .env
          echo "PORT=8080" >> .env
      
      - name: Create start script
        run: |
          echo "#!/bin/bash" > start.sh
          echo "source venv/bin/activate" >> start.sh
          echo "gunicorn --bind 0.0.0.0:\$PORT app:app" >> start.sh
          chmod +x start.sh
      
      - name: Build successful
        run: |
          echo "Production build completed successfully"
          echo "To run the application, use ./start.sh"
          
      # GitHub Actions can build the app, but cannot host Flask directly
      # The files will be available in your repository, but you'll need
      # to manually deploy them to a server that can run Python applications
