name: Flask CI
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8 
      
      - name: Create virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
          python -m pip install gdown  # For Google Drive downloads
      
      - name: Download model from Google Drive
        run: |
          mkdir -p models
          # Using your specific Google Drive file ID and saving with the correct filename
          gdown https://drive.google.com/uc?id=1uw3bfSPDTOAKJusQ16gRfCSS5C9Gl7JS -O models/plant_disease_classification.pth
          # Show the downloaded file
          ls -lh models/
      
      - name: Cache Ollama models
        uses: actions/cache@v3
        with:
          path: ~/.ollama
          key: ollama-models-${{ runner.os }}
      
      - name: Install and setup Ollama
        run: |
          if ! command -v ollama &> /dev/null; then
            curl -fsSL https://ollama.com/install.sh | sh
          fi
          ollama serve &
          sleep 10  # Give Ollama service time to start
          ollama pull mistral
          ollama pull mxbai-embed-large
      
      - name: Print debugging information
        run: |
          echo "Python Version: $(python --version)"
          echo "Working Directory: $(pwd)"
          echo "Contents of models directory: $(ls -lh models/)"
          echo "Installed Packages: $(pip list)"
      
      - name: Run tests
        run: python app.py
